name: Servermanager
main: com.github.letakkak32.servermanager.Main
api-version: 1.19
version: tabcomplete_testing
commands:
  testing:
    description: letakkak32's testing command!
    usage: /testing
  gm:
    permission: servermanager.command.gamemode
  gamemode:
    permission: servermanager.command.gamemode